const { findFAQMatchWithEmbeddings } = require('../faq/matcher');
const { getOpenAIAnswer } = require('../utils/openaiHelper');

module.exports = {
  data: {
    name: 'ask',
    description: 'Ask a question and get an answer from the FAQ or AI.',
    type: 1, // <--- Required for slash command
    options: [
      {
        name: 'question',
        type: 3, // STRING
        description: 'Your question',
        required: true,
      },
    ],
  },
  async execute(interaction) {
    // Optional: If you have a toggle system for enabling/disabling the bot
    if (typeof askEnabled === 'function' && !askEnabled()) {
      return await interaction.reply({
        content: "The bot is temporarily unavailable.",
        ephemeral: true
      });
    }

    // Defer reply immediately to avoid Discord interaction timeouts
    await interaction.deferReply({ ephemeral: true });

    try {
      const question = interaction.options.getString('question');
      const faqMatch = await findFAQMatchWithEmbeddings(question);

      if (faqMatch) {
        await interaction.editReply({
          content: `**(Mod Answer)**\n**Q:** ${question}\n**A:** ${faqMatch.answer}`,
        });
      } else {
        let aiAnswer = null;
        try {
          aiAnswer = await getOpenAIAnswer(question);
        } catch (err) {
          console.error('OpenAI error:', err);
          aiAnswer = "Sorry, there was a problem generating an AI answer. Please try again later.";
        }

        await interaction.editReply({
          content: `**(AI-generated answer)**\n**Q:** ${question}\n**A:** ${aiAnswer}\n\n*Note: This answer was generated by AI. If it doesn't help, please ask in <#support-channel-id>.*`,
        });
      }
    } catch (err) {
      console.error('Error in /ask command:', err);
      // Always use editReply here because we've already deferred
      try {
        await interaction.editReply({
          content: "There was an error executing this command!",
        });
      } catch (editErr) {
        console.error('Failed to edit reply:', editErr);
      }
    }
  },
};
