const { SlashCommandBuilder } = require('discord.js');
const { findFAQMatch } = require('../faq/matcher');
const { getOpenAIAnswer } = require('../utils/openaiHelper');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('ask')
    .setDescription('Ask the support bot a question')
    .addStringOption(option =>
      option.setName('question')
        .setDescription('Your question')
        .setRequired(true)),
  async execute(interaction) {
    const question = interaction.options.getString('question');
    const faqMatch = findFAQMatch(question);

    if (faqMatch) {
      await interaction.reply({
        content: `**(Mod Answer)**\n**Q:** ${question}\n**A:** ${faqMatch.answer}`,
        ephemeral: true
      });
    } else {
      const aiAnswer = await getOpenAIAnswer(question);
      await interaction.reply({
        content: `**(AI-generated answer)**\n**Q:** ${question}\n**A:** ${aiAnswer}\n\n*Note: This answer was generated by AI. If it doesn't help, please ask in <#support-channel-id>.*`,
        ephemeral: true
      });
    }
  }
};
